apiVersion: skaffold/v4beta3
kind: Config
manifests: # telling scaffold where to find the Kubernetes config files (yaml files)
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
    # useDockerCLI: true # <--- This makes Skaffold respect your Docker CLI context
    # useBuildkit: false # Optional: disable BuildKit for easier debugging
  artifacts:
    - image: baraajr11/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: baraajr11/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
